//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_KONTAKTI
    {
        public int ID { get; set; }
        public string KREIRAO_ID { get; set; }
        public string TRENUTNO_KOD_ID { get; set; }
        public string TRENUTNO_GRUPA_ID { get; set; }
        public string FINALIZIRAO_ID { get; set; }
        public string GENDER { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public string ADRESA { get; set; }
        public string PLZ { get; set; }
        public string DRZAVA { get; set; }
        public string GRAD { get; set; }
        public string PREFIX { get; set; }
        public string BROJ { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string BEI { get; set; }
        public string DOSTUPNOST { get; set; }
        public string MOGUCA_INVESTICIJA { get; set; }
        public string KOMENTAR { get; set; }
        public Nullable<System.DateTime> DATETIME_CREATED { get; set; }
        public Nullable<System.DateTime> DATETIME_UPDATED { get; set; }
        public string AKTIVAN { get; set; }
        public int TERMIN_ID { get; set; }
        public string VRACEN_MARKETINGU { get; set; }
        public string VRACENO_SA_KONTROLE { get; set; }
        public string U_PREGOVORIMA { get; set; }
        public string NIJE_DOBIJEN { get; set; }
        public string SALES_NIJE_ZAINTERESOVAN { get; set; }
        public string PRODAT { get; set; }
        public Nullable<System.DateTime> SALES_NIJE_ZAINTERESOVAN_DATE { get; set; }
        public string BROJ2 { get; set; }
        public string BLACKLIST { get; set; }
        public Nullable<System.DateTime> DATUM_DODJELE { get; set; }
        public string FIRMA { get; set; }
        public string BROJ_KARTICA { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
    }
}
