//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_KONTAKTI_OBRISANI
    {
        public int ID { get; set; }
        public int ORIGINAL_ID { get; set; }
        public string FIRMA { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public string ADRESA { get; set; }
        public string PLZ { get; set; }
        public string DRZAVA { get; set; }
        public string GRAD { get; set; }
        public string PREFIX { get; set; }
        public string BROJ { get; set; }
        public string EMAIL { get; set; }
        public string VRSTA_PRODAJE { get; set; }
        public string BROJ_KARTICA { get; set; }
        public Nullable<System.DateTime> VVL_DATUM { get; set; }
        public string KOMENTAR { get; set; }
        public System.DateTime DATETIME_OBRISAN { get; set; }
        public string OBRISAO_ID { get; set; }
        public string OBRISAO_USERNAME { get; set; }
    }
}
