//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTAKT_HISTORY
    {
        public int ID { get; set; }
        public Nullable<int> KONTAKT_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CHANGED_AT { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
    
        public virtual KONTAKT_HISTORY KONTAKT_HISTORY1 { get; set; }
        public virtual KONTAKT_HISTORY KONTAKT_HISTORY2 { get; set; }
    }
}
