//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTAKTI
    {
        public int ID { get; set; }
        public string KREIRAO_ID { get; set; }
        public string TRENUTNO_KOD_ID { get; set; }
        public string TRENUTNO_GRUPA_ID { get; set; }
        public string FINALIZIRAO_ID { get; set; }
        public string GENDER { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public string ADRESA { get; set; }
        public string PLZ { get; set; }
        public string DRZAVA { get; set; }
        public string GRAD { get; set; }
        public string PREFIX { get; set; }
        public string BROJ { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string BEI { get; set; }
        public Nullable<System.DateTime> TERMIN { get; set; }
        public string DOSTUPNOST { get; set; }
        public string MOGUCA_INVESTICIJA { get; set; }
        public string KOMENTAR { get; set; }
        public Nullable<System.DateTime> DATETIME_CREATED { get; set; }
        public Nullable<System.DateTime> DATETIME_UPDATED { get; set; }
        public string AKTIVAN { get; set; }
        public Nullable<int> TERMIN_ID { get; set; }
        public string VRACEN_MARKETINGU { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual AspNetUsers AspNetUsers3 { get; set; }
        public virtual TERMINI TERMINI { get; set; }
    }
}
