//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATISTIKA
    {
        public int ID { get; set; }
        public string AGENT_ID { get; set; }
        public string PROVJERIO { get; set; }
        public string POZVAO { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string BROJ { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
