//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMINI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TERMINI()
        {
            this.KONTAKTI = new HashSet<KONTAKTI>();
        }
    
        public int ID { get; set; }
        public string USER_ID { get; set; }
        public Nullable<System.DateTime> DATUM { get; set; }
        public string NAZIV { get; set; }
        public Nullable<int> KONTAKT_ID { get; set; }
        public Nullable<System.DateTime> DATUM_KRAJA { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONTAKTI> KONTAKTI { get; set; }
    }
}
